#
# Timedance CircleCI Configuration
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    environment:
      TAG: $(sed 's/master/latest/;s/\//\-/' <<<$CIRCLE_BRANCH)
    steps:
      - checkout
      - run: go get -v github.com/spf13/hugo

  test:
    docker:
      - image: circleci/golang:1.11
    steps:
      - run:
          name: tests
          command: echo "test"
  
  deploy:
    docker:
      - image: circleci/golang:1.11
    branches:
      only:
        - master
    steps:
      - checkout
      - run: go get -v github.com/spf13/hugo
      - run:
          name: hugo
          command: hugo
      - run:
          name: deploy
          command: sh deploy.sh www.timedancemusic.com
