#
# Timedance CircleCI Configuration
#
version: 2.0
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    environment:
      TAG: $(sed 's/master/latest/;s/\//\-/' <<<$CIRCLE_BRANCH)
    steps:
      - checkout
      - run: mkdir $HOME/src
      - run: cd $HOME/src
      - run: git clone https://github.com/gohugoio/hugo.git
      - run: cd hugo
      - run: go install --tags extended
      - run:
          name: tests
          command: echo "test"
      - run:
          name: hugo
          command: hugo
      - run:
          name: install dependencies
          command: sudo apt-get update && sudo apt-get install -y awscli
      - run:
          name: deploy
          command: sh deploy.sh www.timedancemusic.com