#
# Timedance CircleCI Configuration
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8 #
    environment:
      TAG: $(sed 's/master/latest/;s/\//\-/' <<<$CIRCLE_BRANCH)

dependencies:
  pre:
    - go get -v github.com/spf13/hugo

test:
  override:
    - echo "test"

deployment:
  prod:
    branch: master
    commands:
      - hugo
      - sh deploy.sh www.timedancemusic.com
