#
# Timedance CircleCI Configuration
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    environment:
      TAG: $(sed 's/master/latest/;s/\//\-/' <<<$CIRCLE_BRANCH)
    steps:
      - checkout
      - run: go get https://github.com/gohugoio/hugo
      - run:
          name: tests
          command: echo "test"
      - run:
          name: hugo
          command: hugo
      - run:
          name: install dependencies
          command: sudo apt-get update && sudo apt-get install -y awscli
      - run:
          name: deploy
          command: sh deploy.sh www.timedancemusic.com