baseurl = "/"
title = "Timedance"
languageCode = "en-gb"

[Params]
  description = "Record label based in Bristol, UK. Run by Batu."
  keywords = "timedance, timedance music, timedance record label, batu, bristol, uk, music, dance music, underground music, records, vinyl, events, music event, techno, electronic, bass"
  author = "Batu"
  twitter_handle = "@timedance_uk"
  site_name = "timedancemusic.com"
  facebook_id = "735348709865504"
  meta_image="timedance-logo.jpg"
  ga_id = "UA-102037964-1"